name: Python Interactive Workflow

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version'
        required: true
        default: '3.10'
        type: choice
        options:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ github.event.inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ github.event.inputs.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions flake8
    
    - name: Test with tox
      run: tox -e py$(echo ${{ github.event.inputs.python-version }} | tr -d .)
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml
      if: ${{ always() }}
